### ISSUE TITLE
Update contract address for faucet in UI check

### ISSUE THREAD

**Issue by slinlee** [slavingia/fweb3.xyz#152]
I'm not at a computer do here is a link to the details for now. 

 https://discord.com/channels/931742630461718578/935583978071679086/949998871201841183

So turns out that because one of the dots of the game is to pull from the faucet, and now that the faucet address has changed, we need to update the website to look at the new faucet address

--
We will want it to check either the new or old address to light up the faucet dot.

**Comment by jester7** [comment]
Updated in #153 , tested with fresh and old wallets, now correctly checks bold old and new matic faucets.
