### ISSUE TITLE
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor

### ISSUE THREAD

**Issue by slavingia** [slavingia/fweb3.xyz#166]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/74396/157342106-f035c0e9-a6bc-405d-beee-93d177c93396.png">

**Comment by archae0pteryx** [comment]
This is a child of a child dep. We need to check and see if the parent packages have updates.
If you run `npm why node-fetch` you'll see that it's in a few packages we use.
