### ISSUE TITLE
Wallet permalink pages

### ISSUE THREAD

**Issue by slavingia** [slavingia/fweb3.xyz#31]
E.g. fweb3.xyz/?wallet=asdifasdf98as9df9sdf

For easy sharing and (to be honest, mostly) testing

**Comment by slinlee** [comment]
This is a question for me to learn, I presume we'll still use polygonscan to get the info from the chain to fill in the dots. But for the first dot, will we just automatically fill it in for the shared pages?

**Comment by slavingia** [comment]
Yep exactly. If any of the other dots are filled, can assume.
