### ISSUE TITLE
Dot 3 use-token isn't activating

### ISSUE THREAD

**Issue by slinlee** [slavingia/fweb3.xyz#32]
Based on initial reports, it's not activating for users who use the faucet website. It works for people who use the contract directly.

One idea is to check for the emitted event.

https://polygonscan.com/address/0x67806adca0fD8825DA9cddc69b9bA8837A64874b#events

**Comment by samwb63** [comment]
When users use the faucet website, transactions seem to post as "internal transactions". There is a separate Polygon endpoint for "internal" transactions. We could make a second call to retrieve this list as well:
`https://api.polygonscan.com/api?module=account&action=txlistinternal&address=[ADDRESS]&startblock=0&endblock=99999999&sort=asc&apikey=[API_KEY]`

**Comment by samwb63** [comment]
@slinlee @slavingia pinging for PR review ^

**Comment by samwb63** [comment]
FYI - with this extra call, we may start hitting rate limits on the Free tier of Polygonscan API.
