### ISSUE TITLE
Optimize Polygonscan API calls to avoid rate limit

### ISSUE THREAD

**Issue by samwb63** [slavingia/fweb3.xyz#36]
Rewrite code so that this stops happening:

> Our internal polygon.js API appears to be invoked twice on page load - the first time without a wallet address defined, and a second time once the address is defined. Perhaps there is a way to invoke only once the wallet address is defined, sparing the first (wasted) calls.

If this isn't good enough, we can reach out to see if we can get a much higher rate limit. Their current plans don't really align with what we need IMO.

**Comment by slavingia** [comment]
We probably should fix the double calls as well, but will start w #1.

**Comment by slinlee** [comment]
agreed.

**Comment by slavingia** [comment]
Hm. It's $199/ mo to increase from just 5 to 10 calls/second limit. Not ideal. I think we should try for #1 as that's quite a bit of moolah for not much better limits.

**Comment by samwb63** [comment]
Fixed in PR #37
