### ISSUE TITLE
Verify smart contract

### ISSUE THREAD

**Issue by slavingia** [slavingia/fweb3.xyz#4]
Smart contract address: `0x95cd50f9d591630db85d95c932bbc704dc0ae92a`

Smart contract code:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.2;

import "@openzeppelin/contracts@4.4.2/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts@4.4.2/token/ERC20/extensions/ERC20Burnable.sol";

contract Fweb3 is ERC20, ERC20Burnable {
    constructor() ERC20("Fweb3", "FWEB3") {
        _mint(msg.sender, 10000000 * 10 ** decimals());
    }
}
```

**Comment by sudhamjayanthi** [comment]
[Check this out if you're using hardhat!](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html)

**Comment by slavingia** [comment]
Anyone should be able to verify, but if no one does and I fail to (by probably Jan 31), I'll just deploy another one via hardhat and verify that one.

**Comment by sudhamjayanthi** [comment]
Tried a couple of different methods (flattening, directly pasting the imports, trying to verify from remix etc), failed to verify. Are you sure this is the exact code? 

The easiest method would be for you to verify using something like hardhat (should take < 1 min, if you have already have the project setup)

**Comment by slavingia** [comment]
Yeah, probably true. But I used Remix, and my guess is because I didn't flatten it, it won't work. What I'll do is just create a new contract using hardhat and verify, updating the website and Discord etc before doing the airdop. Will do on the 31st!

**Comment by slavingia** [comment]
Worked! See last commit for changes I needed to make...
