### ISSUE TITLE
Hitting rate limit on polygonscan

### ISSUE THREAD

**Issue by slinlee** [slavingia/fweb3.xyz#86]
The calls are made from `pages/api/polygon.ts`

For the 9 dots, there are multiple calls made: (in the order they are in the source code right now)

1. tokenBalance - token balance
2. txList - used faucet, deployed contract, voted
3. txListInternal - has used faucet (whoops, this is in here twice?), swapped token
4. tokentx (for erc20 token transactions) - has sent tokens, has burned tokens
5. tokennfttx (for nft transactions) - has minted nft

This often results in the page not loading all the dots correctly. The fifth dot (minted an nft) is the usual symptom.

**Comment by slinlee** [comment]
We could do a few things:

- make sure we're not making redundant calls
- cache results locally if the dot is True already
- spread the calls across different services like alchemy or open sea?
- add in timeouts #84

**Comment by slavingia** [comment]
seems to be resolved for now.
