### ISSUE TITLE
Add message to explain what connecting the wallet does on main site

### ISSUE THREAD

**Issue by Bschuster3434** [slavingia/fweb3.xyz#93]
From Vinyl, Mecha Penguin creator after using the website:

I'd like to see how the contract interacts with my wallet, taking in consideration all the phishing and things that have been going on

Is there a way we can give a notice to folks to let them know why we’re asking for a connection? Or maybe make it optional if you are okay giving your own address.

**Comment by slinlee** [comment]
Yeah, great point. 

Fyi, at this point the UI only connects to the wallet for two reasons:
1. It's the first step, and useful for learning how that works.
2. Gets the wallet address. The rest of the dots go through polygonscan to get the data.

**Comment by slavingia** [comment]
i'll work on this next. should be easy. i think generally we will want some design metaphor to explain what's happening under the hood/allow them to go direct to polygonscan, but having our own UI as well.
