### ISSUE TITLE
Add a message on the website if the user is seeking verification, verified or a winner.

### ISSUE THREAD

**Issue by Bschuster3434** [slavingia/fweb3.xyz#96]
https://fweb3.xyz/?wallet=0x510d1bd177E1f6062317E377F0A9CEBe91BC8FBb

It should be easy to tell in the users page if they are seeking verification, verified or a winner. Something simple near the top would be helpful.

**Comment by slavingia** [comment]
good idea. a crown/trophy emoji on the top right or next to their wallet addr would be a super easy start
