### ISSUE TITLE
Fix auto tests for walkthrough

### ISSUE THREAD

**Issue by slinlee** [slavingia/fweb3.xyz#97]
The locators need to be updated, preferably using data attributes.

To run the tests:
- run `npm run dev`
- in a separate terminal run `npm run e2e`
- click 'run all tests`

cc @epan

**Comment by slinlee** [comment]
nvm, the tests run successfully as they are for now. Switching to using data attributes is just a nice to have.

**Comment by slavingia** [comment]
not sure if we should use data attributes; i think the new standard is ARIA labels to be accessibility-compliant

**Comment by slinlee** [comment]
> not sure if we should use data attributes; i think the new standard is ARIA labels to be accessibility-compliant

These wouldn't be `aria-`, but `data-cy`

https://docs.cypress.io/guides/references/best-practices#Selecting-Elements 

/hattip @epan

**Comment by epan** [comment]
Yeah technically you could target anything including aria attributes if you wanted to. Using a scheme for attributes to select by for testing alone is probably cleaner. Not all elements you want to select will have aria attributes etc
